module.exports = {
  BRIDGES_RECEIVED: "BRIDGES_RECEIVED",
  SINGLE_BRIDGE_RECEIVED: "SINGLE_BRIDGE_RECEIVED",
  REMOVE_BRIDGE: "REMOVE_BRIDGE",
  FAVORITE_RECEIVED: "FAVORITE_RECEIVED",
  FAVORITE_REMOVED: "FAVORITE_REMOVED"
};
